apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user1-mcoa-rb
  namespace: open-cluster-management-observability
subjects:
- kind: User
  name: user1
roleRef:
  kind: Role
  name: user1-cluster-role
  apiGroup: rbac.authorization.k8s.io
